services:
  db:
    image: postgres:16-alpine
    environment:
      POSTGRES_DB: task-management
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres
    ports:
      - "5432:5432"
    volumes:
      - ./data:/var/lib/postgresql/data
  app:
    image: task-management:v2
    build:
      context: /
    environment:
      SPRING_DATASOURCE_URL: jdbc:postgresql://db:5432/task-management
#      SPRING_PROFILES_ACTIVE: init
    ports:
      - "8080:8080"