name: Test
services:
  db:
    image: postgres:16-alpine
    environment:
      POSTGRES_DB: task-management
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres
    ports:
      - "5432:5432"
    volumes:
      - ./postgres/data:/var/lib/postgresql/data
      - ./postgres/sql/data.sql/:/docker-entrypoint-initdb.d/create_tables.sql
    networks:
      - app-network
  app:
    image: task-management:v1
    build:
      context: /
    environment:
      SPRING_DATASOURCE_URL: jdbc:postgresql://db:5432/task-management
    ports:
      - "8080:8080"
    networks:
      - app-network
    depends_on:
      - db
networks:
  app-network:
    driver: bridge