-- Создание таблицы пользователей
CREATE TABLE users
(
    id       BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    email    VARCHAR(255) UNIQUE,
    password VARCHAR(255),
    role     VARCHAR(255) CHECK (role IN ('ADMIN', 'CLIENT'))
);

-- Создание таблицы задач
CREATE TABLE task
(
    id          BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    author_id   BIGINT,
    executor_id BIGINT,
    title       VARCHAR(255),
    details     VARCHAR(255),
    priority    VARCHAR(255) CHECK (priority IN ('HIGH', 'MIDDLE', 'LOW')),
    status      VARCHAR(255) CHECK (status IN ('PENDING', 'IN_PROGRESS', 'COMPLETED'))
);

-- Создание таблицы комментариев
CREATE TABLE comment
(
    id        BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    author_id BIGINT NOT NULL,
    task_id   BIGINT NOT NULL,
    details   VARCHAR(255)
);

-- Добавление внешних ключей
ALTER TABLE comment
    ADD CONSTRAINT FK_comment_author FOREIGN KEY (author_id) REFERENCES users;

ALTER TABLE comment
    ADD CONSTRAINT FK_comment_task FOREIGN KEY (task_id) REFERENCES task;

ALTER TABLE task
    ADD CONSTRAINT FK_task_author FOREIGN KEY (author_id) REFERENCES users;

ALTER TABLE task
    ADD CONSTRAINT FK_task_executor FOREIGN KEY (executor_id) REFERENCES users;
-- Инициализация начальных пользователей
insert into users(email, password, role)
values ('admin@email.com', 'admin', 'ADMIN');
insert into users(email, password, role)
values ('test@email.com', 'test', 'CLIENT');
